### ISSUE TITLE
두 파일의 크기를 비교하는 함수 작성 sizecmp()

### ISSUE THREAD

**Issue by minhyukcho5904** [ChoiJuEon/Assignment2_old#1]
void sizecmp(void)
{
    
    int size1 = (int)stat1.st_size;
    int size2 = (int)stat2.st_size;

    printf("size compare\n");

    if (size1 > size2)
        printf("text1 is bigger\n");
    else if (size1 < size2)
        printf("text2 is bigger\n");
    else
        printf("sizes are equal\n");
}

**Comment by minhyukcho5904** [comment]
확인해주시고, 수정할 점 있으면 알려주세요.

**Comment by llffmmgg** [comment]
적절하게 실행됩니다 ~

**Comment by minhyukcho5904** [comment]
그럼 이대로 진행하겠습니다
