### ISSUE TITLE
두 개의 파일 블락 수를 비교하는 함수 작성 blockcmp()

### ISSUE THREAD

**Issue by minhyukcho5904** [ChoiJuEon/Assignment2_old#2]
void blockcmp(void)
{

    int blk1 = (int)stat1.st_blocks;
    int blk2 = (int)stat2.st_blocks;

    printf("block compare\n");

    if (blk1 > blk2)
    {
        printf("text1 is bigger\n\n");
    }
    else if (blk1 < blk2)
    {
        printf("text2 is bigger\n\n");
    }
    else
    {
        printf("size are equal\n\n");
    }
}

**Comment by minhyukcho5904** [comment]
요것도 체크 부탁드립니다.

**Comment by llffmmgg** [comment]
적절하게 실행됩니다 ~

**Comment by minhyukcho5904** [comment]
넵. 이것도 이대로 진행하겠습니다.
